CREATE TABLE pessoa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_completo VARCHAR(150) NOT NULL,
    nome_social VARCHAR(150),
    cpf VARCHAR(11),
    data_nascimento DATE,
    email VARCHAR(160),
    telefone VARCHAR(30),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_pessoa_cpf UNIQUE (cpf)
);

CREATE TABLE papel_academia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(80) NOT NULL,
    descricao VARCHAR(300),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_papel_academia_nome UNIQUE (nome)
);

CREATE TABLE pessoa_papel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_id BIGINT NOT NULL,
    papel_academia_id BIGINT NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_pessoa_papel_pessoa FOREIGN KEY (pessoa_id) REFERENCES pessoa (id),
    CONSTRAINT fk_pessoa_papel_papel FOREIGN KEY (papel_academia_id) REFERENCES papel_academia (id),
    CONSTRAINT uk_pessoa_papel UNIQUE (pessoa_id, papel_academia_id),
    CONSTRAINT ck_pessoa_papel_periodo CHECK (data_fim IS NULL OR data_fim >= data_inicio)
);

CREATE TABLE permissao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(100) NOT NULL,
    nome VARCHAR(120) NOT NULL,
    descricao VARCHAR(300),
    CONSTRAINT uk_permissao_codigo UNIQUE (codigo)
);

CREATE TABLE perfil_acesso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(80) NOT NULL,
    descricao VARCHAR(300),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_perfil_acesso_nome UNIQUE (nome)
);

CREATE TABLE perfil_permissao (
    perfil_acesso_id BIGINT NOT NULL,
    permissao_id BIGINT NOT NULL,
    PRIMARY KEY (perfil_acesso_id, permissao_id),
    CONSTRAINT fk_perfil_permissao_perfil FOREIGN KEY (perfil_acesso_id) REFERENCES perfil_acesso (id),
    CONSTRAINT fk_perfil_permissao_permissao FOREIGN KEY (permissao_id) REFERENCES permissao (id)
);

CREATE TABLE conta_acesso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_id BIGINT NOT NULL,
    email VARCHAR(160) NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    perfil_acesso_id BIGINT NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    troca_senha_obrigatoria BOOLEAN NOT NULL DEFAULT TRUE,
    ultimo_acesso_em TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_conta_acesso_pessoa UNIQUE (pessoa_id),
    CONSTRAINT uk_conta_acesso_email UNIQUE (email),
    CONSTRAINT fk_conta_acesso_pessoa FOREIGN KEY (pessoa_id) REFERENCES pessoa (id),
    CONSTRAINT fk_conta_acesso_perfil FOREIGN KEY (perfil_acesso_id) REFERENCES perfil_acesso (id)
);

CREATE TABLE matricula (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_id BIGINT NOT NULL,
    codigo VARCHAR(30) NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT uk_matricula_codigo UNIQUE (codigo),
    CONSTRAINT fk_matricula_pessoa FOREIGN KEY (pessoa_id) REFERENCES pessoa (id),
    CONSTRAINT ck_matricula_periodo CHECK (data_fim IS NULL OR data_fim >= data_inicio),
    CONSTRAINT ck_matricula_status CHECK (status IN ('ATIVA', 'TRANCADA', 'CANCELADA', 'ENCERRADA'))
);

CREATE TABLE faixa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    ordem INTEGER NOT NULL,
    idade_minima INTEGER,
    quantidade_maxima_graus INTEGER NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_faixa_nome UNIQUE (nome),
    CONSTRAINT uk_faixa_ordem UNIQUE (ordem),
    CONSTRAINT ck_faixa_idade CHECK (idade_minima IS NULL OR idade_minima >= 0),
    CONSTRAINT ck_faixa_graus CHECK (quantidade_maxima_graus >= 0)
);

CREATE TABLE historico_graduacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_id BIGINT NOT NULL,
    faixa_id BIGINT NOT NULL,
    grau INTEGER NOT NULL,
    data_graduacao DATE NOT NULL,
    responsavel_id BIGINT,
    observacao VARCHAR(500),
    CONSTRAINT fk_graduacao_pessoa FOREIGN KEY (pessoa_id) REFERENCES pessoa (id),
    CONSTRAINT fk_graduacao_faixa FOREIGN KEY (faixa_id) REFERENCES faixa (id),
    CONSTRAINT fk_graduacao_responsavel FOREIGN KEY (responsavel_id) REFERENCES pessoa (id),
    CONSTRAINT ck_graduacao_grau CHECK (grau >= 0)
);

CREATE INDEX idx_pessoa_nome ON pessoa (nome_completo);
CREATE INDEX idx_pessoa_papel_pessoa ON pessoa_papel (pessoa_id);
CREATE INDEX idx_matricula_pessoa ON matricula (pessoa_id);
CREATE INDEX idx_graduacao_pessoa_data ON historico_graduacao (pessoa_id, data_graduacao);

INSERT INTO papel_academia (nome, descricao) VALUES
    ('Aluno', 'Pessoa matriculada como praticante'),
    ('Instrutor', 'Pessoa autorizada a conduzir treinos'),
    ('Responsável', 'Responsável legal ou financeiro por aluno'),
    ('Recepção', 'Pessoa responsável pelo atendimento'),
    ('Financeiro', 'Pessoa responsável pela gestão financeira');

INSERT INTO permissao (codigo, nome) VALUES
    ('ALUNO_VISUALIZAR', 'Visualizar alunos'),
    ('ALUNO_CADASTRAR', 'Cadastrar alunos'),
    ('ALUNO_EDITAR', 'Alterar alunos'),
    ('ALUNO_INATIVAR', 'Inativar alunos'),
    ('GRADUACAO_VISUALIZAR', 'Visualizar graduações'),
    ('GRADUACAO_ALTERAR', 'Alterar graduações'),
    ('GRADUACAO_APROVAR', 'Aprovar graduações'),
    ('USUARIO_GERENCIAR', 'Gerenciar usuários'),
    ('PERFIL_GERENCIAR', 'Gerenciar perfis e permissões');

INSERT INTO perfil_acesso (nome, descricao) VALUES
    ('Aluno', 'Acesso pessoal do aluno'),
    ('Instrutor', 'Gestão de alunos e graduações'),
    ('Recepção', 'Cadastro e manutenção de alunos'),
    ('Administrador', 'Acesso administrativo completo');

INSERT INTO perfil_permissao (perfil_acesso_id, permissao_id)
SELECT perfil.id, permissao.id
FROM perfil_acesso perfil
CROSS JOIN permissao
WHERE perfil.nome = 'Administrador';

INSERT INTO faixa (nome, ordem, idade_minima, quantidade_maxima_graus) VALUES
    ('Branca', 1, NULL, 4),
    ('Cinza', 2, 4, 4),
    ('Amarela', 3, 7, 4),
    ('Laranja', 4, 10, 4),
    ('Verde', 5, 13, 4),
    ('Azul', 6, 16, 4),
    ('Roxa', 7, 16, 4),
    ('Marrom', 8, 18, 4),
    ('Preta', 9, 19, 6),
    ('Coral vermelha e preta', 10, 50, 0),
    ('Coral vermelha e branca', 11, 57, 0),
    ('Vermelha', 12, 67, 0);
