spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  h2:
    console:
      enabled: false

app:
  security:
    jwt-secret: ${JWT_SECRET}
    token-duration: ${JWT_DURATION:PT2H}
